### ISSUE TITLE
Colon expected error on valid json (version 3.2.3)

### ISSUE THREAD

**Issue by okomarov** [josdejong/jsonrepair#101]
```
jsonrepair.jsonrepair('{"test": "hello\n\nworld"}')

Uncaught JSONRepairError: Colon expected at position 23
    at throwColonExpected (/Users/okomarov/Documents/repos/myrepo/node_modules/.pnpm/jsonrepair@3.2.3/node_modules/jsonrepair/lib/cjs/jsonrepair.js:543:11)
```

For context, the version 3.2.0 does not throw.

**Comment by josdejong** [comment]
In v3.2.1 an issue was fixed where a missing quote can mess up a whole document, see #97. To improve this, jsonrepair is no longer fixing unescaped newline characters in a string, but instead assumes that encountering a newline character means a missing double quote and it will insert it right before the return.

I'm open to ideas but I don't see a way to cater for both cases. My assumption is that a missing quote is more common than an unescaped newline character, that's why I think it is a good idea to cater for the first case. Does that make sense?

**Comment by okomarov** [comment]
Thank you for the quick reply! 

For context, we're using this to parse json returned by ChatGPT which often does not escape new lines (especially the gtp-3.5 and text completion models), while we never get non-terminated strings.

We're obviously biased towards fixing unescaped new lines. Maybe we could call the repair with an option, in one case you prioritise escaping newlines, in the other case missing quotes. I can see this workflow in a double try catch actually, try one then the other!

As a side note, since we use renovate with auto-merge on minor and patch updates, the regression could have been avoided if the change was marked as major (which I think is, as it breaks behaviour in a backward incompatible way)

Let me know what you think about the _option_ approach and if you need a hand on this

**Comment by hstanford** [comment]
Quick thought - parseString is already capable of overshooting the end of the string and walking back past a comma.

Would this logic be acceptable?
- newlines don't stop parsing of strings
- when finding a closing `"`, check that the characters following the `"` are acceptable (`/\s*[,\]}]/` ?)
- if not, assume that a quote has been missed, and try walking back and place a `"` in the first acceptable place it finds (in the position before`/\s*,\s*/`, throw if it encounters any other chars first?)

This should handle both
```
{
  "hello": "world,
  "foo": "bar",
}
```

and 
```
{
  "hello": "world
  world",
  "foo": "bar",
}
```

I appreciate how difficult these problems are - this library has to guess intention!
The newline fixing behaviour is really important as it's the most likely error in LLM-generated JSON objects with large string values.

**Comment by josdejong** [comment]
> As a side note, since we use renovate with auto-merge on minor and patch updates, the regression could have been avoided if the change was marked as major (which I think is, as it breaks behaviour in a backward incompatible way)

Sorry for the trouble @okomarov. Yeah maybe I should have marked it as a breaking change. I find that sometimes hard to determine, every fix changes the behavior in _some_ way, normally for the better though :S.

@hstanford thanks for your input. This idea crossed my mind too. Basically, assume the string is valid until really proven otherwise. I was a bit hesitant because I'm not sure if that introduces other unwanted side-effects, but it can work I think. Let's see if we can solve it like that.

As a temporary workaround: can't you guys politely ask ChatGPT to properly escape the return characters? 😜

**Comment by josdejong** [comment]
Fixed now via 51a4de9 and published in `v3.2.4`, it's quit a solid solution I think. Can you give it a try?

> I appreciate how difficult these problems are - this library has to guess intention!

@hstanford It is a really challenging puzzle 😎 . Whilst implementing a fix with your proposal for example I ran into the issue that the logic requiring the end quote of a string to be followed by a valid delimiter collides with the case `{"a" 2}` which is a JSON document with a missing colon between key and value that should be repaired 😅.

**Comment by okomarov** [comment]
@josdejong We've been running the fixed version in prod now and no issues so far, thanks again.

**Comment by josdejong** [comment]
🎉 thanks for the feedback, good to hear.

**Comment by vladshcherbin** [comment]
Just had same problem with 3.2.4, while 3.2.0 is working fine 😭

**Comment by josdejong** [comment]
@vladshcherbin can you share an example that is going wrong for you now? 

The original reported example is working in v3.2.4 (and will escape the unescaped newlines):

```js
jsonrepair.jsonrepair('{"test": "hello\n\nworld"}')
// '{"test": "hello\\n\\nworld"}'
```

**Comment by josdejong** [comment]
Ok good to hear all is good 😅
