### ISSUE TITLE
Not able to access jsonrepairTransform from 'jsonrepair/stream'

### ISSUE THREAD

**Issue by vsrinivaskanuparthi** [josdejong/jsonrepair#118]
Cannot find module 'jsonrepair/stream' or its corresponding type declarations.

**Comment by josdejong** [comment]
Thanks for reporting. How can I reproduce your issue?

**Comment by vsrinivaskanuparthi** [comment]
I did "npm install jsonrepair" and trying to access the jsonrepairTransform as per the example from the npm repository. and then it is giving error while trying to access jsonrepairTransform from 'jsonrepair/stream'.

**Comment by vsrinivaskanuparthi** [comment]
@josdejong I am using an hapi.js framework typescript based application. i simply did npm install ("npm install jsonrepair") and followed the streams example given in the npm repo. and when i try to access jsonrepairTransform() method from 'jsonrepair/stream' it is giving me the error. can you give an example how can i use jsonrepairTransform() method in typescript ??

![image](https://github.com/josdejong/jsonrepair/assets/49976340/8073c65b-f785-4cbc-84f4-42d4edb1e117)

**Comment by josdejong** [comment]
I tried in a plain TypeScript project, and indeed there TypeScript isn't able to find the type definitions. The types are defined in [the `exports` property](https://github.com/josdejong/jsonrepair/blob/main/package.json#L15-L26) in `package.json`. 

It turns out that your `tsconfig` should be using `moduleResolution` of `node16` or `nodenext`, see [StackOverflow](https://stackoverflow.com/a/74551879/1262753).

Here is an example of a working TS project: 

https://stackblitz.com/edit/jsonrepair-stream-example?file=package.json,tsconfig.json,index.ts
